### ISSUE TITLE
Heroku [deployement] 'NameError: name 'model' is not defined'

### ISSUE THREAD

**Issue by chiragkava** [robmarkcole/yolov5-flask#13]
Works fine in local machine but when i try to deploy on heroku and upload the image for inference it gives error 500
internal server error.

Here is the heroku log

![image](https://user-images.githubusercontent.com/61086004/120273636-66dfec00-c2cc-11eb-9f56-079e846da08b.png)

Any idea why this is happening. sorry if it is trivial question.

Steps to recreate
1. Clone this repo
2. modify requirements file (just copy yolov5 req.txt to current one)
3. Add procfile (web: gunicorn app:app --log-level debug)
4. deploy on heroku

**Comment by robmarkcole** [comment]
I dont know anything about Heroku - might be more logs somewhere with error installing yolo

**Comment by robmarkcole** [comment]
t
@chiragkava try latest release on master

**Comment by chiragkava** [comment]
Thanks for the help, there was problem from my side did a clean install of all library (updated version) and worked for me !
