### ISSUE TITLE
NameError: name 'model' is not defined

### ISSUE THREAD

**Issue by RRighart** [robmarkcole/yolov5-flask#19]
Hi, I tried your Flask script and received the following error: "NameError: name 'model' is not defined".
It origins probably from this line:
```
model = torch.hub.load(
        "ultralytics/yolov5", "yolov5s", pretrained=True, force_reload=True, autoshape=True
    )  # force_reload = recache latest code
```
I was wondering if I can find the model thay you are using somewhere in your repo or is it at Ultralytics?
Thank you very much in advance!

**Comment by robmarkcole** [comment]
This should load the default model from torch_hub, perhaps the api changed?

**Comment by RRighart** [comment]
Thank you for your help!
I have run the same line of code in a Kaggle notebook and there it is doing well:

```
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /root/.cache/torch/hub/master.zip
YOLOv5 🚀 v6.1-25-gcaf7ad0 torch 1.9.1+cpu CPU

Fusing layers... 
Model Summary: 213 layers, 7225885 parameters, 0 gradients, 16.5 GFLOPs
Adding AutoShape...  
```
I have checked the packages in requirements.txt but everything seems fine. Any suggestions would be welcome!

**Comment by robmarkcole** [comment]
Maybe it cannot access the internet somehow? Workaround would be to cache the model whilst building the container

**Comment by Prakhar0809** [comment]
> Hi, I tried your Flask script and received the following error: "NameError: name 'model' is not defined". It origins probably from this line:
> 
> ```
> model = torch.hub.load(
>         "ultralytics/yolov5", "yolov5s", pretrained=True, force_reload=True, autoshape=True
>     )  # force_reload = recache latest code
> ```
> 
> I was wondering if I can find the model thay you are using somewhere in your repo or is it at Ultralytics? Thank you very much in advance!

I'm facing the same problem but the solution mentioned above didn't quite work for me. Is there any other way to get past this problem?

**Comment by robmarkcole** [comment]
Maybe try with just the args shown in https://pytorch.org/hub/ultralytics_yolov5/
