### ISSUE TITLE
Not able to open yolo video detection results on browser

### ISSUE THREAD

**Issue by macpreet** [robmarkcole/yolov5-flask#20]
Can you guide me how to display video results on browser as the detection results in the mp4 format along with bounding boxes are opening in the local media players but black box appears when opening in any browser. Is this a format issue ?  
P.S :  Using flask api to display results on frontend.

**Comment by robmarkcole** [comment]
The api requires images, not videos. You can pull frames out of the video (e.g. 1 frame per second) and process those 

https://github.com/robmarkcole/yolov5-flask/blob/f1ee21bc3b14cdf1a1ea3bc95111a8db31172216/restapi.py#L21
