### ISSUE TITLE
Images saved in runs/exp etc so cat image is returned by webapp.py

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/yolov5-flask#34]
Each saved image is saved to runs/exp, runs/exp2 etc, not sure how to control this behaviour. Result is the cats image is returned by webapp.py each time

**Comment by Mak-3** [comment]
i can solve this

**Comment by robmarkcole** [comment]
Please see (and contribute :) ) at https://github.com/robmarkcole/yolov5-flask/pull/36
